<% response.setHeader("Pragma", "no-cache");%>
<% response.setHeader("Cache-Control", "no-store");%>
<% response.setDateHeader("Expires", -1);%> 
<html>
    <head>
        <title>The Geo Data Portal - Error Encountered</title>
        <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
        <META HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE">
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
        <link rel="stylesheet" href="css/usgs/common.css" type="text/css" />
        <link rel="stylesheet" href="css/usgs/usgs_style_main.css" type="text/css" />
        <link rel="stylesheet" href="css/common.css" type="text/css" />

        <script src="js/log4javascript/log4javascript.js" type="text/javascript"></script>
        <jsp:include page="../../js/jquery/jquery.jsp">
            <jsp:param name="debug-qualifier" value="false"/>
        </jsp:include>
        <script src="js/constants.js" type="text/javascript"></script>
    </head>
    <body>
        <jsp:include page="../../template/header.jsp" />
        <div id="error_header_div"><h3>Error Encountered</h3></div>
        <div id="error_description">
            The Web server encountered an unexpected condition that prevented it from fulfilling your request.<br /><br />
            This is a 'catch-all' error generated by the Web server. Basically something has gone wrong, but the server can 
            not be more specific about the error condition in its response to you. In addition to the 500 error notified 
            back to you, the Web server should have generated an internal error log which gives more details of what 
            went wrong. You can try <a href="mailto:gdp@usgs.gov?subject=Geo Data Portal Error">contacting the system administrator</a> 
            for this application to find out what went wrong.
            <br />
            You may try going back to the <a href=".">front page</a>.
        </div>
        <br />
        <jsp:include page="../../template/footer.jsp" />
    </body>
</html>